version: 2
updates:
  - package-ecosystem: 'npm'
    directory: /
    commit-message:
      prefix: 'chore(deps)'
  - package-ecosystem: 'docker'
    directory: /
    commit-message:
      prefix: 'chore(deps)'
