version: 2

updates:
  - package-ecosystem: 'npm'
    directory: /
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: 'docker'
    directory: /
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore(deps)'
