# https://docs.codeclimate.com/docs/advanced-configuration
version: '2'
exclude_patterns:
  - 'dist/'
  - 'docker/'
  - 'e2e/'
  - 'examples/'
  - 'node_modules/'
  - 'test-reports/'
  - 'tests/'
  - 'tmp/'
  - '.codeclimate.yml'
  - '.dockerignore'
  - '.gitignore'
  - '.lintstagedrc.js'
  - '.nvmrc'
  - '.prettierignore'
  - '.prettierrc.yml'
  - '.releaserc.yml'
  - '.travis.yml'
  - 'CODEOWNERS'
  - 'Dockerfile'
  - 'LICENSE'
  - 'karma-test-shim.ts'
  - 'karma.conf.ts'
  - '**/*.json'
  - '**/*.md'
  - '**/*.yml'
  - '**/*.spec.ts'
  - '**/*.fixtures.ts'
plugins:
  structure:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        typescript:
