# https://docs.codeclimate.com/docs/advanced-configuration
version: '2'
exclude_patterns:
  - '.circleci/'
  - '.github/'
  - '.husky/'
  - 'dist/'
  - 'docker/'
  - 'docs/'
  - 'e2e/'
  - 'examples/'
  - 'node_modules/'
  - 'test-reports/'
  - 'tests-e2e/'
  - 'tests-failures/'
  - 'tests-performance/'
  - 'tests/'
  - 'tmp/'
  - 'libs/ng-mocks/src/index.ts'
  - 'libs/ng-mocks/src/lib/mock-builder/promise/types.ts'
  - 'libs/ng-mocks/src/lib/mock-builder/types.ts'
  - 'libs/ng-mocks/src/lib/mock-component/types.ts'
  - 'libs/ng-mocks/src/lib/mock-directive/types.ts'
  - 'libs/ng-mocks/src/lib/mock-helper/format/types.ts'
  - 'libs/ng-mocks/src/lib/mock-module/types.ts'
  - 'libs/ng-mocks/src/lib/mock-pipe/types.ts'
  - 'libs/ng-mocks/src/lib/mock-render/types.ts'
  - 'libs/ng-mocks/src/lib/mock-service/types.ts'
  - '.codeclimate.yml'
  - '.commitlintrc.yml'
  - '.dockerignore'
  - '.editorconfig'
  - '.eslintignore'
  - '.eslintrc.yml'
  - '.gitignore'
  - '.lintstagedrc.js'
  - '.nvmrc'
  - '.prettierignore'
  - '.prettierrc.yml'
  - '.releaserc.yml'
  - 'CODEOWNERS'
  - 'Dockerfile'
  - 'LICENSE'
  - 'empty.ts'
  - 'karma.conf.ts'
  - 'renovate.json'
  - 'test.ts'
  - 'webpack.config.js'
  - '**/*.fixtures.ts'
  - '**/*.json'
  - '**/*.md'
  - '**/*.sh'
  - '**/*.spec.ts'
  - '**/*.yml'
  - '**/karma.conf.js'
plugins:
  structure:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        typescript:
checks:
  method-complexity:
    config:
      threshold: 25
  return-statements:
    enabled: false
  similar-code:
    config:
      threshold: 150
  file-lines:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 100
