os: linux
language: node_js
node_js:
  - 10
dist: trusty
addons:
  chrome: stable
git:
  autocrlf: false
install:
  - npm install
jobs:
  include:
    - name: 'Unit Tests'
      script:
        - WITH_COVERAGE=1 npm run test
        - ./node_modules/coveralls/bin/coveralls.js < test-reports/coverage/lcov/lcov.info
    - name: 'E2E'
      script:
        - npm run e2e
before_cache:
  - rm -Rf $HOME/.npm/anonymous-cli-metrics.json
  - mkdir -p $HOME/.npm/_cacache/index-v5/34/8e
  - echo '' > $HOME/.npm/_cacache/index-v5/34/8e/30c54cce758990bcd1b33114c4aa8a9e5a25c152ac39d9feab22b7e13e00
cache:
  npm: true
  directories:
    - $HOME/.node-gyp
    - node_modules
