os: linux
language: node_js
node_js:
  - 10
dist: trusty
addons:
  chrome: stable
git:
  autocrlf: false
install:
  - npm install
jobs:
  include:
    - name: 'Unit Tests'
      script:
        - npm run test:angular-versions
    - name: 'E2E'
      script:
        - npm run e2e
cache:
  npm: true
  directories:
    - $HOME/.node-gyp
    - node_modules
