os: linux
language: node_js
node_js:
  - 10
dist: trusty
addons:
  chrome: stable
install:
  - npm install
script:
  - npm run test:angular-versions
  - npm run e2e
cache:
  npm: false
  directories:
    - /home/travis/.npm
    - /home/travis/.node-gyp
