os: linux
language: node_js
node_js:
  - v14.15.3
dist: trusty
addons:
  chrome: stable
git:
  autocrlf: false
install:
  - npm install
jobs:
  include:
    - name: 'Essential checks'
      script:
        - npm run prettier:check
        - npm run lint
        - npm run ts:check
        - WITH_COVERAGE=1 npm run test
        - npm run build:docs
        - npm run e2e
      after_success:
        # https://coveralls.io/github/ike18t/ng-mocks
        - ./node_modules/.bin/coveralls < test-reports/coverage/lcov/lcov.info

        # https://codecov.io/gh/ike18t/ng-mocks
        - ./node_modules/.bin/codecov -f test-reports/coverage/lcov/lcov.info --disable=gcov

        # https://codeclimate.com/github/ike18t/ng-mocks
        - >-
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          > $HOME/codeclimate
        - chmod +x $HOME/codeclimate
        - $HOME/codeclimate before-build
        - >-
          $HOME/codeclimate format-coverage
          -t lcov test-reports/coverage/lcov/lcov.info
          -o test-reports/codeclimate.json
        - >-
          $HOME/codeclimate upload-coverage
          -r 8d19fbe26762a46ed2e12de542b38738418a96d961cfaca0d757e0a7390ced69
          -i test-reports/codeclimate.json
    - name: 'E2E Angular 5 6 7 8 9'
      script:
        - npm run build
        - npm run i:a5 && npm run i:a6 && npm run i:a7 && npm run i:a8 && npm run i:a9
        - npm run clear:a5 && npm run clear:a6 && npm run clear:a7 && npm run clear:a8 && npm run clear:a9
        - npm run s:a5 && npm run s:a6 && npm run s:a7 && npm run s:a8 && npm run s:a9
        - npm run s:test:a5 && npm run s:test:a6 && npm run s:test:a7 && npm run s:test:a8 && npm run s:test:a9
        - npm run test:a5 && npm run test:a6 && npm run test:a7 && npm run test:a8 && npm run test:a9
    - name: 'E2E Angular 10 11 12'
      script:
        - npm run build
        - npm run i:a10 && npm run i:a11 && npm run i:a12
        - npm run clear:a10 && npm run clear:a11 && npm run clear:a12
        - npm run s:a10 && npm run s:a11 && npm run s:a12
        - npm run s:test:a10 && npm run s:test:a11 && npm run s:test:a12
        - npm run test:a10 && npm run test:a11 && npm run test:a12
before_cache:
  - echo '' > $HOME/.npm/anonymous-cli-metrics.json
  - mkdir -p $HOME/.npm/_cacache/index-v5/34/8e
  - echo '' > $HOME/.npm/_cacache/index-v5/34/8e/30c54cce758990bcd1b33114c4aa8a9e5a25c152ac39d9feab22b7e13e00
cache:
  npm: true
  directories:
    - $HOME/.node-gyp
    - node_modules
