version: '3'

services:
  ng-mocks:
    build: ./
    volumes:
      - .:/app
      - /npm
      - /app/node_modules
      - /app/e2e/a5es5/node_modules
      - /app/e2e/a5es2015/node_modules
      - /app/e2e/a6/node_modules
      - /app/e2e/a7/node_modules
      - /app/e2e/a8/node_modules
      - /app/e2e/a9/node_modules
      - /app/e2e/a10/node_modules
      - /app/e2e/a11/node_modules
